Refactor transport z12 14
openmaptiles/openmaptiles pull request #1207
Opened 2021-09-02 02:05 UTC by ZeLonewolf

This PR is a refactor, and makes no changes in functionality.

The purpose of this PR is to refactor the logic in the z12-z14 transportation layer to increase readability and reduce code complexity.

2021-09-02 10:40 UTC, ZeLonewolf commented on layers/transportation/transportation.sql
> -                     ) AND man_made <> 'pier'
Thanks, I need to look at this more closely.  The layer sizes changed so clearly I didn't achieve a 1:1 refactor here.

2021-09-02 12:06 UTC, Falke-Design requested changes

2021-09-02 12:06 UTC, Falke-Design commented on layers/transportation/transportation.sql
> +                         WHEN man_made = 'pier' AND NOT ST_IsClosed(geometry) THEN TRUE -- Only linear piers, not pier areas
`AND service NOT IN ('driveway', 'parking_aisle')` is missing here

2021-09-02 12:06 UTC, Falke-Design commented on layers/transportation/transportation.sql
> +                    END
`AND man_made <> 'pier'` is missing

2021-09-02 12:06 UTC, Falke-Design commented on layers/transportation/transportation.sql
> +                    WHEN zoom_level = 14 THEN
```suggestion
                    WHEN zoom_level >= 14 THEN
```

2021-09-02 13:58 UTC, ZeLonewolf commented on layers/transportation/transportation.sql
> +                         WHEN man_made = 'pier' AND NOT ST_IsClosed(geometry) THEN TRUE -- Only linear piers, not pier areas
I don't understand this comment - that exact line is present at line 369.  Can you clarify?

2021-09-02 14:08 UTC, ZeLonewolf reviewed
Thanks for detailed review

2021-09-02 14:19 UTC, Falke-Design commented on layers/transportation/transportation.sql
> +                         WHEN man_made = 'pier' AND NOT ST_IsClosed(geometry) THEN TRUE -- Only linear piers, not pier areas
Yes, but line 369 is another `WHEN` then line 370. So it is needed here too

2021-09-05 09:56 UTC, Falke-Design requested changes
This now very complex too, I don't know if it makes sense to change from complex to complex and then add maybe some unwanted bugs

2021-09-05 09:56 UTC, Falke-Design commented on layers/transportation/transportation.sql
> +                    CASE WHEN highway IN ('unclassified', 'residential') THEN TRUE
`AND man_made <> 'pier'` is missing

2021-09-05 09:56 UTC, Falke-Design commented on layers/transportation/transportation.sql
> +                    CASE WHEN highway = 'service' AND service NOT IN ('driveway', 'parking_aisle') THEN TRUE
`highway = 'service'` is new? Does this break some current logic?

2021-09-05 09:56 UTC, Falke-Design commented on layers/transportation/transportation.sql
> +                         WHEN man_made = 'pier' AND NOT ST_IsClosed(geometry) THEN TRUE  -- Only linear piers, not pier areas
`AND service NOT IN ('driveway', 'parking_aisle')` is missing

2021-09-05 09:56 UTC, Falke-Design commented on layers/transportation/transportation.sql
> +                         WHEN highway_class(highway, public_transport, man_made, construction) NOT IN ('track', 'path', 'service', 'service_construction', 'pier') THEN TRUE
`AND service NOT IN ('driveway', 'parking_aisle')` is missing

2021-09-05 16:31 UTC, ZeLonewolf commented on layers/transportation/transportation.sql
> +                         WHEN highway_class(highway, public_transport, man_made, construction) NOT IN ('track', 'path', 'service', 'service_construction', 'pier') THEN TRUE
Where are you saying it's missing?  It's covered in 369 (include all service roads other than driveway/parking_aisle) and line 371 (exclude service roads)

2021-09-05 16:34 UTC, ZeLonewolf commented on layers/transportation/transportation.sql
> +                    CASE WHEN highway IN ('unclassified', 'residential') THEN TRUE
Are you saying for the case of `highway=unclassified` + `man_made=pier`?  I don't see that being a necessary check.  If it's tagged as unclassified/residential, adding pier tagging shouldn't pull it out of z12.

2021-09-05 16:36 UTC, ZeLonewolf commented on layers/transportation/transportation.sql
> +                    CASE WHEN highway = 'service' AND service NOT IN ('driveway', 'parking_aisle') THEN TRUE
I don't think so?  You need that check, otherwise you capture `highway=` values other than `service`.  Another option is to do a `service <> ''` instead but I felt the explicit highway check made things more clear.

2021-09-05 16:38 UTC, ZeLonewolf commented on layers/transportation/transportation.sql
> +                         WHEN man_made = 'pier' AND NOT ST_IsClosed(geometry) THEN TRUE  -- Only linear piers, not pier areas
`service` is a sub-tagging of `highway=service`, it's not clear to me why you would need a check outside of `highway=service` filters.

2021-09-05 16:56 UTC, ZeLonewolf commented
Okay, I agree I haven't really solved the "too confusing" problem here, let me have another go at it.

2021-09-05 18:51 UTC, Falke-Design commented on layers/transportation/transportation.sql
> +                         WHEN highway_class(highway, public_transport, man_made, construction) NOT IN ('track', 'path', 'service', 'service_construction', 'pier') THEN TRUE
Ah okay, I didn't know this, I only compared the old sql with the new one

2021-09-05 18:51 UTC, Falke-Design commented on layers/transportation/transportation.sql
> +                         WHEN man_made = 'pier' AND NOT ST_IsClosed(geometry) THEN TRUE  -- Only linear piers, not pier areas
Ah okay, I didn't know this, I only compared the old sql with the new one

2021-09-05 18:52 UTC, Falke-Design commented on layers/transportation/transportation.sql
> +                    CASE WHEN highway = 'service' AND service NOT IN ('driveway', 'parking_aisle') THEN TRUE
Same here, I didn't know this, I only compared the old sql with the new one. So this looks valid with your explanation

2021-09-05 18:53 UTC, Falke-Design commented on layers/transportation/transportation.sql
> +                    CASE WHEN highway IN ('unclassified', 'residential') THEN TRUE
It was in the old sql checked. I don't know if it makes sense. But if you say it is not necessary, then I believe you.

2021-09-05 23:11 UTC, ZeLonewolf commented
Okay, I think I've got it sorted.  Hopefully this is easier to look at this time.  I was able to compact the changes and also come up with a cleaner solution to the `pier` and `service` filters.  I did find some bugs as noted in the top comment which I suspect is the reason for the -0.1% change at z12 (which was inadvertently bringing in construction roads that it shouldn't have).

2021-09-20 06:07 UTC, TomPohys commented
Great work! Thank you very much!

2021-09-20 06:07 UTC, TomPohys approved these changes

2021-09-20 06:07 UTC, merged