Fix paths and tracks in transportation layer z12 and z13
openmaptiles/openmaptiles pull request #1334
Opened 2022-01-02 18:43 UTC by lazaa32

This PR fixes a bug that causes that `track` lines disappear at z13. This bug was introduced in https://github.com/openmaptiles/openmaptiles/pull/1190, which adds rendering of paths and tracks at z12 and z13.

Before this PR:
z12: lines with `route_rank = 1` are added (no matter what `highway`).
z13: lines with `route_rank BETWEEN 1 AND 2` and `highway = 'path'` are added.
-> tracks with `route_rank=1` are added at z12 but not at z13.
GIF of z11, z12, z13, z14
![master](https://user-images.githubusercontent.com/19833762/147885914-cb92241e-e375-494c-8da9-23fc28d8d4af.gif)

After this PR
z12: lines with `route_rank = 1` and `highway IN ('path', 'track')` are added.
z13: lines with `route_rank BETWEEN 1 AND 2` and `highway IN ('path', 'track')` are added .
-> only tracks and paths are added at z12 and z13 (which was IMHO the goal of https://github.com/openmaptiles/openmaptiles/pull/1190)
GIF of z11, z12, z13, z14
![pr](https://user-images.githubusercontent.com/19833762/147885950-17c1f8a7-a94a-4432-8a06-71e9995489c3.gif)

GIF showing the difference at z13.
![diff_z13](https://user-images.githubusercontent.com/19833762/147885986-2b6ab45a-c35b-4fb7-a995-d9d2ef91d68d.gif)

@ZeLonewolf could you please check this PR as it is related to your work? I hope that I understood your goal to add rendering of paths and tracks correctly.

2022-01-02 20:33 UTC, ZeLonewolf requested changes
This PR should just be a one-line change to `transportation_filter_z12()` as noted in my review comments.

2022-01-02 20:33 UTC, ZeLonewolf commented on layers/transportation/transportation.sql
> +                              WHEN hl.highway IN ('track', 'path') THEN n.route_rank = 1
Instead of this, add an entry for track to `layers/transportation/class.sql` in the function `transportation_filter_z12()`

2022-01-02 20:33 UTC, ZeLonewolf commented on layers/transportation/transportation.sql
> +                                                                )
This change is not correct, track should have universal rendering at z13, not conditional rendering, which will be fixed with the change noted in above in `transportation_filter_z12()`

2022-01-02 21:03 UTC, lazaa32 commented on layers/transportation/transportation.sql
> +                              WHEN hl.highway IN ('track', 'path') THEN n.route_rank = 1
`track` added to `transporation_filter_z12` function.

2022-01-02 21:03 UTC, lazaa32 commented on layers/transportation/transportation.sql
> +                                                                )
Reverted.

2022-01-02 21:06 UTC, lazaa32 commented
> This PR should just be a one-line change to `transportation_filter_z12()` as noted in my review comments.

This adds all `track` lines at z12 and z13.
@TomPohys can you please confirm this is OK?

2022-01-02 21:16 UTC, ZeLonewolf reviewed
Pending confirmation with screen shots, this looks correct.

2022-01-03 16:27 UTC, lazaa32 commented
@ZeLonewolf this PR atm with your suggestions added +2.7% at z12 and +1.8% at z13 which is quite a lot.

I need to clarify one thing. Was your intention to:
- at z12
  -  add the most important **tracks** (`route_rank=1`)
- at z13
  - add more important **tracks** (`route_rank between 1 and 2`)
  - add more important **paths** (`route_rank between 1 and 2`)
  
Or was your intention to:
- at z12
  -  add all **tracks**
- at z13
  - add all **tracks**
  - add more important **paths** (`route_rank between 1 and 2`)
 
Because with your review suggestion the latter is now implemented.
Thanks for the clarification.

2022-01-03 16:35 UTC, ZeLonewolf commented
The intent is for all tracks to render, which would be parity with osm-carto, and is what I described in my writeup for #1190.  The 2.7% increase, in my opinion, is a necessary growth in order to provide that parity.  The zoom filtering that I describe in that ticket is:

**Zoom 12**
* All highway=track
* Paths that are members of international & national hiking routes (network=iwn/network=nwn) (rank=1)

**Zoom 13**
* All highway=track
* Paths that are members of a hiking route, or have a name, sac_scale, osmc:symbol, or colour (rank=1,2)

**Zoom 14**
* All highway=track
* All highway=path

2022-01-04 15:02 UTC, lazaa32 commented
After discussion with @TomPohys and @daliborjanak:
Adding all tracks at z12 and z13 increases tiles size too much and it adds too many lines at some places.
![diff_z12](https://user-images.githubusercontent.com/19833762/148076530-e830ed71-09e8-4ce5-857f-a64b4374bcc5.gif)

We decided to use the same filter (`route_rank=1` at z12 and `route_rank between 1 and 2` at z13) both for tracks and paths.

2022-01-04 15:25 UTC, farfromrefug commented
@lazaa32 a little bit out of subject. what tool.did you use to do the gif sliding comparaison? seems very useful

2022-01-04 15:30 UTC, lazaa32 commented
MapLibre Compare plugin
https://github.com/maplibre/maplibre-gl-compare

2022-01-04 17:45 UTC, farfromrefug commented
@lazaa32 awesome thanks ! i am migrating mapbox mbview to maplibre. will try to add support for that plugin and and drag and drop support of mbtiles. really need something like this!

2022-01-05 06:17 UTC, TomPohys approved these changes

2022-01-05 06:27 UTC, TomPohys commented
Thank you!

2022-01-05 06:28 UTC, merged