Zlw housenumber collapse
openmaptiles/openmaptiles pull request #1562
Opened 2023-07-07 02:36 UTC by ZeLonewolf

Fixes #1558 

This PR collapses housenumber values into the form min(housenumber)-max(housenumber) for cases where housenumber is a semi-colon separated list.

![image](https://github.com/openmaptiles/openmaptiles/assets/3254090/0342bf2c-01f0-4f31-893a-cdf00f20bc00)

![image](https://github.com/openmaptiles/openmaptiles/assets/3254090/100f09e5-530a-4afd-8e04-353acc733150)

Location (localhost link):
http://localhost:8080/data/v3/#19/41.7278712/-72.2072315

2023-07-07 04:02 UTC, 1ec5 commented on layers/housenumber/housenumber_display.sql
> +  -- Check if the input string contains a semi-colon separator
It’s very common to tag `addr:housenumber` with a range, as an alternative to enumerating each number in the range. The most common range separator is a hyphen, although some features use ` to ` to avoid the ambiguity in https://github.com/openmaptiles/openmaptiles/issues/1558#issuecomment-1624649822. It would make sense for the raw range separator to become an en dash too. If that sounds too easy, consider that a tag value might contain a range followed by a semicolon followed by another value.

2023-07-07 11:56 UTC, ZeLonewolf commented on layers/housenumber/housenumber_display.sql
> +  -- Check if the input string contains a semi-colon separator
There is probably not a perfect processing that will work in all cases - is there logic you would suggest to handle these cases?

2023-07-07 15:25 UTC, 1ec5 commented on layers/housenumber/housenumber_display.sql
> +  -- Check if the input string contains a semi-colon separator
If you’re comfortable with ignoring Queens-style addresses, you could replace `-` with `;` upfront before the rest of the routine.

2023-07-07 16:19 UTC, ZeLonewolf commented on layers/housenumber/housenumber_display.sql
> +  -- Check if the input string contains a semi-colon separator
That would produce very wrong results for Hawaiian addresses.

2023-07-07 17:50 UTC, 1ec5 commented on layers/housenumber/housenumber_display.sql
> +  -- Check if the input string contains a semi-colon separator
Oh, does Hawaii use Queens-style addressing too?

2023-07-07 18:10 UTC, ZeLonewolf commented on layers/housenumber/housenumber_display.sql
> +  -- Check if the input string contains a semi-colon separator
I'm not familiar with Queens-style addressing, but in Hawaii (with the exception of the city of Honolulu), all addresses are prefixed with a 2-digit code indicating what sector of the island you're at.  For example, in ʻAiea the code is 99, so you would have addresses in the form `99-12 <street name>`. Conceptually, if anyone's tagged semi-colon separated addresses, you could have housenumbers that might look like `99-12;99-14`.  Treating the hyphen/dash as a delimiter would produce either `99-14` or `12-99`, both of which would be horribly wrong.  Further, on just a standard address of `99-12 Whatever Street`, if we treated the dash as a delimiter _and sorted it_, you'd end up with `12-99` which would indicate a location on a different sector of the island.  So hence my concern.

2023-07-07 18:37 UTC, ZeLonewolf commented on layers/housenumber/housenumber_display.sql
> +  -- Check if the input string contains a semi-colon separator
From what I've read it sounds like yes, this is the same situation as Queens-style addressing, and I don't think it would be prudent to cause bad address numbers for an entire US state.

2023-07-07 19:11 UTC, 1ec5 commented on layers/housenumber/housenumber_display.sql
> +  -- Check if the input string contains a semi-colon separator
What if this routine avoids sorting if something looking like a range appears anywhere in the raw data? Either you could look for a hyphen and call it a day, or you could check whether the hyphen separates values in ascending order.

It’s probably worth starting a broader tagging discussion about resolving this ambiguity. I could see a case for eliminating ranges from the tagging scheme and always enumerating the middle values, as long as more renderers and geocoders introduce behavior like what you’ve implemented. However, the well-established [Karlsruhe schema](https://wiki.openstreetmap.org/w/index.php?oldid=2323041#Using_interpolation_to_mark_many_houses_along_a_way) specifically allows for ranges. There are probably also edge cases to consider: what happens if a building is signposted with its start and end numbers but nothing in between? Ironically, you’d have to tag it as not a range in order for it to look like a range in OpenMapTiles.

2023-07-07 22:09 UTC, ZeLonewolf commented on layers/housenumber/housenumber_display.sql
> +  -- Check if the input string contains a semi-colon separator
At the risk of inserting yet more en_US localization, perhaps the logic can be "if the string contains a dash, convert all semi-colons to commas", which would better serve the Queens/Hawaii problem.

Example: https://www.openstreetmap.org/node/2882804955

2023-07-07 22:13 UTC, pnorman commented on layers/housenumber/housenumber_display.sql
> +$$ LANGUAGE plpgsql;
This function could be SQL, not plpgsql, for better performance.

2023-07-07 22:14 UTC, pnorman commented on layers/housenumber/housenumber_display.sql
> +$$ LANGUAGE plpgsql;
Same as other function. This could be a fairly simple CASE statement

2023-07-07 22:17 UTC, pnorman requested changes
plpgsql functions take significantly longer to be called than SQL, particularly if the SQL gets inlined then there is no cost to calling the function. Both functions should be declared as `IMMUTABLE`

2023-08-08 22:49 UTC, pnorman reviewed
SQL looks good - no opinion on the overall effect.

2023-09-13 06:33 UTC, TomPohys commented
Thanks a lot! It looks good. Is it ready to be merged?

2023-09-13 09:01 UTC, ZeLonewolf commented
Yes, ready here👍

2023-09-13 09:08 UTC, TomPohys approved these changes

2023-09-13 09:09 UTC, merged